simple-login/.env.example, simple-login/.eslintignore, simple-login/.eslintrc.json, simple-login/.husky/pre-commit, simple-login/README.md, simple-login/package-lock.json, simple-login/package.json, simple-login/pages/_app.tsx, simple-login/pages/index.tsx, simple-login/services/providers/NearWalletProvider.tsx, simple-login/services/providers/constants.ts, simple-login/yarn.lock
Added new Queries replacing the old ones, added new Types
- new Readme file
- Husky with pre-commit script running typecheck && eslint before commit
- eslint with airbnb-typescript
- adds title tag to head of index.tsx
=> [feat] new simple-login

simple-minter/pages/_app.tsx
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1203057060566209
- https://app.asana.com/0/0/1203201173904530
=> feat: add error message when dev key is not valid

simple-marketplace/.env, simple-marketplace/.env.example, simple-marketplace/components/BuyModal/BuyModal.tsx, simple-marketplace/components/BuyModal/BuyModalInfo.tsx, simple-marketplace/components/Header.tsx, simple-marketplace/components/HeroSection.tsx, simple-marketplace/components/Item.tsx, simple-marketplace/components/Items.tsx, simple-marketplace/hooks/useStoreNfts.ts, simple-marketplace/hooks/useTokenListData.ts, simple-marketplace/pages/index.tsx, simple-marketplace/types/types.ts, simple-marketplace/utils/getCachedImages.ts, simple-marketplace/utils/index.ts
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1203178937939396
=> feat: referral and layout fixing

simple-marketplace/.env.example, simple-marketplace/components/BuyModal/BuyModalInfo.tsx, simple-marketplace/config/constants.ts
* Making the examples a bit more polished and realword
* Made the referral workable for folks trying on testnet to change right in the config
=> feat: improve referral default

simple-marketplace/.env.example, simple-marketplace/README.md, simple-marketplace/components/BuyModal/BuyModalInfo.tsx
@microchipgnu do we need to do any changes on the nextjs side for this?
=> Change name to affiliate from referral in ENV vars

simple-token-drop/README.md
=> Simple token drop README

contract-deployer/README.md
=> Update Contract-Deployer README.md

blogchain/README.md
=> Update Blogchain README.md

simple-token-drop/src/app/Minter.tsx, simple-token-drop/src/app/page.tsx
=> 💄  Simple Token Drop UI improvements

starter-next/README.md, starter-vite/README.md
=> remove space from tools

ai-chat/README.md, ai-minter/src/hooks/useMint.ts, blogchain/README.md, contract-deployer/README.md, marketplace/README.md, minter/README.md, nft-stripe-checkout/README.md, simple-token-drop/README.md, starter-next/.env.example, starter-next/.gitignore, starter-next/README.md, starter-next/src/app/layout.tsx, starter-vite/.env.example, starter-vite/.gitignore, starter-vite/README.md, starter-vite/src/App.tsx
=> starter readmes

marketplace/.env.example, marketplace/src/components/Item.tsx
=> Update Card UI + Add .env.example

marketplace/src/app/page.tsx, marketplace/src/components/Item.tsx, marketplace/src/components/Items.tsx
=> Fix Marketplace Grid UI

starter-next/README.md
=> Starter readme update

minter/.env, minter/.env.example, minter/.gitignore, minter/README.md, minter/src/app/layout.tsx, minter/src/config/setup.ts, minter/src/hooks/useMint.ts, starter-next/README.md, starter-vite/README.md
=> add minter docs

blogchain/README.md, simple-token-drop/README.md
=> git fix use cases

ai-minter/.env.example, ai-minter/README.md, ai-minter/src/components/Minter.tsx, ai-minter/src/config/setup.ts, ai-minter/src/hooks/useMint.ts
- Add proxy contract to relay minting
- Fix typo in model selector
- Improve readme
=> AI minter improvements

minter/src/config/setup.ts
=> fix config minter

ai-minter/README.md
=> fix ai minter readme

simple-token-drop/src/app/Minter.tsx, simple-token-drop/src/app/constants.ts, simple-token-drop/src/app/serverMint.ts
=> Added testnet proxy contract

marketplace/src/app/layout.tsx
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1206610615854792
=> fix marketplace

blogchain/src/app/typings.ts, blogchain/src/components/create-post.tsx, blogchain/src/hooks/useBlogPosts.tsx, blogchain/src/hooks/useGetBlogPostMetadata.tsx, blogchain/src/hooks/useLatestBlogs.tsx, blogchain/src/hooks/useLatestPosts.tsx, blogchain/src/hooks/useUserBlogs.tsx, blogchain/src/hooks/useUserPosts.tsx
=> :bug: fix blogchain types and data return

simple-token-drop/src/app/constants.ts, simple-token-drop/src/app/serverMint.ts, simple-token-drop/vercel.json
=> Fix server minting on simple token drop

simple-token-drop/src/app/Minter.tsx
=> Add isDrop flag in simple-token-drop

contract-deployer/package.json, contract-deployer/pnpm-lock.yaml, contract-deployer/src/app/globals.css, contract-deployer/src/app/layout.tsx, contract-deployer/src/app/page.tsx, contract-deployer/src/components/Social.tsx, contract-deployer/src/components/Success.tsx, contract-deployer/src/config/setup.ts, contract-deployer/src/hooks/useDeployContract.ts, contract-deployer/src/lib/utils.ts
=> Contract deployer socials widget and success page

nft-stripe-checkout/src/app/globals.css, nft-stripe-checkout/src/app/page.tsx, nft-stripe-checkout/src/components/connect-wallet.tsx, nft-stripe-checkout/src/components/social.tsx
resemble more like other projects
=> fix design and instructions

starter-vite/package.json, starter-vite/pnpm-lock.yaml, starter-vite/src/App.tsx
=> fix vite example

ai-minter/src/hooks/useMint.ts, contract-deployer/src/hooks/useDeployContract.ts, minter/src/hooks/useMint.ts
=> Add Default Values to prevent form dom errors

contract-deployer/src/app/page.tsx, contract-deployer/src/lib/utils.ts
=> contract-deployer: Fix Transaction error

ai-minter/README.md, marketplace/README.md, minter/README.md, nft-stripe-checkout/README.md, nft-stripe-checkout/src/lib/constants.ts, simple-token-drop/.env.example, simple-token-drop/README.md, simple-token-drop/src/app/constants.ts, starter-next/README.md, starter-next/src/app/layout.tsx, starter-vite/README.md
=> fix pre-setup instructions,deploy links & fallback envs

ai-chat/src/components/social.tsx, ai-minter/src/components/Social.tsx, blogchain/src/components/social.tsx, contract-deployer/src/components/Social.tsx, marketplace/src/components/Social.tsx, minter/src/components/Social.tsx, nft-stripe-checkout/src/components/social.tsx, simple-token-drop/src/components/Social.tsx, starter-next/src/components/Social.tsx, starter-vite/src/Social.tsx
=> Remove Use Template Buttons

bounties/asset_burning.md, bounties/daily_art_battle.md, bounties/dynamic_minsta.md, bounties/nft_staking.md, bounties/open_bounty.md
=> Change Reward format in Bounties

starter-next/src/app/layout.tsx, starter-vite/src/App.tsx
=> Fix starter-next/vite window

bounties/agent_plugins.md
Adds Agent Plugin Bounties
___
documentation
___
- Added a new markdown file `bounties/agent_plugins.md` to document the Agent Plugin Bounties for Bitte.
- The documentation includes:
- An introduction to Bitte's mission and the importance of Agent Plugins.
- An overview of the bounty program and the rewards offered.
- Detailed functionality requirements for the plugins.
- Submission guidelines, including how to apply, required deliverables, and evaluation criteria.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>agent_plugins.md</strong><dd><code>Add Agent Plugin Bounties Documentation</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
=> Add Agent Plugin Bounties

coingecko-ai-plugin/README.md
documentation
___
- Updated the cover image URL in the README file.
- Added a new detail image at the end of the README file.
- Removed the `alt` attribute from an existing detail image in the README file.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>README.md</strong><dd><code>Update cover and detail images in README</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
coingecko-ai-plugin/README.md
<li>Updated the cover image URL.<br> <li> Added a new detail image at the end of the document.<br> <li> Removed the <code>alt</code> attribute from an existing detail …
=> Update coingecko detail and cover images

README.md
=> Update README.md add Indexer

README.md
Reverts Mintbase/templates#153
___
documentation
___
- Reverted the addition of the 'GraphQL Indexer' section in the README.md file.
- Updated the introduction to Mintbase.js Templates to remove references to the indexer.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>README.md</strong><dd><code>Revert addition of 'GraphQL Indexer' section in README</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
README.md
<li>Removed the 'GraphQL Indexer' section.<br> <li> Updated the introduction to Mintbase.js Templates.<br>
</details>
</td>
<td><a href="https://github.com/Mintbase/templates/pull/180/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f …
=> Revert "Update README.md add Indexer"

cowswap-ai-plugin/README.md
documentation
___
- Updated the cover image URL in the README.md file.
- Added a new detail image at the end of the README.md file.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>README.md</strong><dd><code>Update images in README.md for CoWSwap-AI</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
cowswap-ai-plugin/README.md
<li>Updated the cover image URL.<br> <li> Added a new detail image at the end of the document.<br>
</details>
</td>
<td><a href="https://github.com/Mintbase/templates/pull/181/files#diff-5f0d4c9838836a99f4d174f8e90a6fe244a1992e438000731be642cea3695e26" …
=> Update README.md cowswap images

blogchain/README.md, blogchain/package.json, blogchain/pnpm-lock.yaml, blogchain/src/app/layout.tsx, blogchain/src/components/app-providers.tsx, blogchain/src/components/create-blog.tsx, blogchain/src/components/create-post.tsx, blogchain/src/components/footer.tsx, blogchain/src/components/header.tsx, blogchain/src/components/hero.tsx, blogchain/src/components/social.tsx, blogchain/src/components/user-blogs.tsx, blogchain/src/components/user-posts.tsx
___
enhancement, documentation
___
- Replaced all instances of `useMbWallet` with `useBitteWallet` across multiple components.
- Updated context provider from `MintbaseWalletContextProvider` to `BitteWalletContextProvider`.
- Changed footer link and button text from Mintbase to Bitte.
- Updated social media title from Mintbase Templates to Bitte Templates.
- Updated metadata creator in layout from Mintbase to Bitte.
- Updated README to reflect changes from …
=> update blogchain project to Bitte

ai-minter/README.md, ai-minter/package.json, ai-minter/pnpm-lock.yaml, ai-minter/src/app/page.tsx, ai-minter/src/components/NearWalletSelector.tsx, ai-minter/src/components/Provider.tsx, ai-minter/src/components/Social.tsx, ai-minter/src/components/Success.tsx, ai-minter/src/config/setup.ts, ai-minter/src/hooks/useMint.ts, blogchain/README.md
___
enhancement, documentation
___
- Replaced all references to Mintbase with Bitte across various files.
- Updated wallet hooks and context providers to use Bitte.
- Renamed configuration setup to Bitte.
- Updated README and package.json to reflect the new branding and dependencies.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
<td>
<details> …
=> Bitte Protocol AI Minter

starter-next/README.md, starter-next/package.json, starter-next/pnpm-lock.yaml, starter-next/src/app/layout.tsx, starter-next/src/app/page.tsx, starter-next/src/components/NearWalletSelector.tsx, starter-next/src/components/Social.tsx
___
enhancement, documentation
___
- Replaced all instances of Mintbase wallet with Bitte wallet across the project, including context providers and hooks.
- Updated project metadata, including titles, descriptions, and social media sharing information to reflect Bitte branding.
- Improved formatting in several components and documentation files.
- Updated `@mintbase-js/react` dependency to version 0.6.5.
- Refined README to provide clearer instructions and …
=> Bitte Update for starter-next

marketplace/README.md, marketplace/package.json, marketplace/pnpm-lock.yaml, marketplace/src/app/layout.tsx, marketplace/src/app/page.tsx, marketplace/src/components/BuyModal/BuyModalInfo.tsx, marketplace/src/components/Landing.tsx, marketplace/src/components/header.tsx, marketplace/src/hooks/useStoreNfts.ts
___
Enhancement, Documentation
___
- Replaced `MintbaseWalletContextProvider` with `BitteWalletContextProvider` across the application.
- Updated callback URL logic and renamed wallet setup variables.
- Changed all instances of `useMbWallet` to `useBitteWallet`.
- Updated page titles, descriptions, and landing page content to reflect `Bitte` branding.
- Updated README to reflect `Bitte` branding and updated code examples to use double quotes.
- Updated …
=> update marketplace template to bitte

minter/README.md, minter/package.json, minter/pnpm-lock.yaml, minter/src/app/layout.tsx, minter/src/app/page.tsx, minter/src/components/NearWalletSelector.tsx, minter/src/components/Provider.tsx, minter/src/components/Social.tsx, minter/src/config/setup.ts, minter/src/hooks/useMint.ts
___
Enhancement, Documentation
___
- Replaced all instances of `Mintbase` with `Bitte` across various components and configuration files.
- Updated wallet references from `useMbWallet` to `useBitteWallet`.
- Adjusted social media links and titles to reflect Bitte branding.
- Updated README and package.json to reflect the new project name and author.
___
<table><thead><tr><th></th><th align="left">Relevant …
=> bitte update for minter template

nft-stripe-checkout/README.md, nft-stripe-checkout/package.json, nft-stripe-checkout/pnpm-lock.yaml, nft-stripe-checkout/src/app/layout.tsx, nft-stripe-checkout/src/app/page.tsx, nft-stripe-checkout/src/components/connect-wallet.tsx, nft-stripe-checkout/src/components/providers/wallet-provider.tsx, nft-stripe-checkout/src/components/social.tsx, nft-stripe-checkout/src/lib/constants.ts
___
enhancement, documentation
___
- Replaced all instances of Mintbase wallet with Bitte wallet across multiple files.
- Updated project metadata, constants, and social media titles to reflect Bitte branding.
- Improved code formatting and readability in several files.
- Updated README and package.json to reflect the new branding and latest dependencies.
___
<table><thead><tr><th></th><th align="left">Relevant …
=> update stripe checkout
